version: '3.1'
services:
  db:
    image: postgres:11.2
    restart: always
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    env_file:
      - .env
    volumes:
      - ./.db:/var/lib/postgresql

networks:
  default:
    external:
      name: neko_caffe_network
